# pubspec.yaml
name: resources_used_lints
version: 0.1.0
publish_to: none

environment:
  sdk: "^3.4.0"

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4

description: Custom lints for formatting comments on use of AI/external resources and reflections.