# pubspec.yaml
name: resources_used_lints
version: 0.1.0

environment:
  sdk: "^3.4.0"

dependencies:
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  custom_lint_builder: ^0.8.1

description: Lint rules for documentation of resources used in CSE 340.

repository: https://github.com/jszh/Resources-Used-Lints
